### ISSUE TITLE
RxPHP v2.x

### ISSUE THREAD

**Issue by davidwdan** [ReactiveX/RxPHP#101]
I've started work on RxPHP v2 with the goal of bringing it's behavior closer to RxJS 4/5.  You can see the progress [here](https://github.com/davidwdan/RxPHP/tree/2.x)

Here's a list of the changes I've made so far:

- PHP 7 is a minimum requirement
- It now uses the [interop event-loop](https://github.com/async-interop/event-loop) ( ~~defaults to [ReactPHP](https://github.com/WyriHaximus/reactphp-async-interop-loop), but~~ it'll work with any library that support the interop loop, including ~~[Icicle](https://github.com/icicleio/icicle)~~, [ReactPHP](https://github.com/async-interop/event-loop), [Amphp](https://github.com/amphp/loop) and [KoolKode](https://github.com/koolkode/async))
- It uses a static scheduler (you no longer pass the scheduler through subscribe).  For the most part, the user will not have to worry about the scheduler.
- ~~The event loop auto starts with `register_shutdown_function`.  The less the user has to worry about the underlying event loop and scheduler, the better.~~
- We had some non-standard names for operators, because they were reserved words in PHP, those have all been renamed (`of`, `empty`, `do`, `catch`, `switch`).  Aliases of the old names were left for backwards compatibility.
- Lots of cleanup
- Included [Allow custom operators](https://github.com/ReactiveX/RxPHP/pull/93)

### v1 example
With v1, the user has to know when to create a new scheduler and has to be familiar with event loops, which can be confusing and easy to mess up.

```PHP
$loop      = \React\EventLoop\Factory::create();
$scheduler = new \Rx\Scheduler\EventLoopScheduler($loop);

\Rx\Observable::interval(1000)
    ->take(5)
    ->flatMap(function ($i) {
        return \Rx\Observable::just($i + 1);
    })
    ->subscribe(new \Rx\Observer\CallbackObserver(function ($e) {
        echo $e, PHP_EOL;
    }), $scheduler);

$loop->run();

```

### v2 example
With v2, we pick the correct default scheduler for each operator that requires one, which you can override as needed (setting a scheduler should be the exception, not the rule).  In the example below, `interval` and `of` already have the correct default scheduler, so the user doesn't need to define one.
```PHP
\Rx\Observable::interval(1000)
    ->take(5)
    ->flatMap(function ($i) {
        return \Rx\Observable::of($i + 1);
    })
    ->subscribe(function ($e) {
        echo $e, PHP_EOL;
    });
```

### v2 with `Loop::execute` example
You can also use it within `Loop::execute`, without making any changes to your Rx code
```PHP
\Interop\Async\Loop::execute(function () {
    \Rx\Observable::interval(1000)
        ->take(5)
        ->flatMap(function ($i) {
            return \Rx\Observable::of($i + 1);
        })
        ->subscribe(function ($e) {
            echo $e, PHP_EOL;
        });
});
```
### Remaining Items and Ideas
- [x] If possible, combine `subscribe` and `subscribeCallback`
- [x] Add support for `async-interop/promise` 
- [x] Move react promise support to stand alone project or remove 
- [x] ~~Look into simplifying `AnonymousObservable` by moving auto dispose code to `Observable`~~
- [x] Figure out how to get it to work with HHVM
- [ ] Add a `forEach` method to `Observable` that'll behave like `subscribe` except it'll block until complete (for use with synchronous code) similar to RxJava.

Before I move this to the ReactiveX/RxPHP repo, I'd like to get some feedback on the changes above as well as other changes or pain points that we should address with v2.

**Comment by mbonneau** [comment]
I have concerns in depending on async-interop because they are currently pre-release.

Could async-interop make breaking changes that would cause BC breaks in this library if we were to depend on their loop and promise specs?

(I do realize that we use reactphp libraries that are pre-1.0 also, but those have been stable for years)

Should we wait for a roadmap of some sort from async-interop before adding them as a dependency?

**Comment by davidwdan** [comment]
@mbonneau I'm not a fan of waiting.  There are very few places where we interactive with the interop-loop (currently only in the EventLoopScheduler and Promise), so I think we'll be able to handle any changes without BC breaks.

**Comment by kelunik** [comment]
@davidwdan: When do you plan to release it? The React adapter isn't in any way stable yet.

**Comment by kelunik** [comment]
> You can also manually start the loop if you need to it to run sooner. ie. for synchronous code

What does _"run it sooner"_ mean here?

Any reason why you default to the React loop instead of just letting the user install a loop implementation themselves? That's how it's designed. The loop implementation can automatically set itself as a factory then.

**Comment by davidwdan** [comment]
@kelunik The only reason to default to an event loop (I chose React because that's what v1 used) is to make it easier for people not familiar with the event loop to get started.

We can reworked it to only include React as a dev dependency, so you can run the demos if you clone the repo, without having to pick a event loop.

As far as the `v2 example with manual run`, it's just there to show how to mimic the behavior of v1, where you have to run the loop manually.

**Comment by davidwdan** [comment]
@kelunik I removed the dependency on react, so its stability won't be an issue for release.

As far as I know, only [koolkode](https://github.com/koolkode/async) has a stable adapter released.  It would be nice to have a couple more before release, but not 100% necessary. 

The other issue is the lack of libraries that support the async-interop loop.  We've created a "[temporary](https://github.com/voryx/ReactLoopInterfaceForAsyncInteropLoop)" solution that'll bridge that gap for ReactPHP libraries.

**Comment by kelunik** [comment]
> The other issue is the lack of libraries that support the async-interop loop. We've created a "temporary" solution that'll bridge that gap for ReactPHP libraries.

Amp v2.0.0 is nearly finished, but we wait for the interop spec to be finalized. As soon as that's done, all our libraries should be ported pretty quickly.

When do you plan to release v2?

**Comment by mbonneau** [comment]
My concern for this was to hide as much async-interop as possible in case there are breaking changes over there when they do release.

Waiting for the spec to be completed would be ideal. I was not able to find a timetable for that or gauge based on the open issues and PRs when that would be.

As far as depending on a non-final version: We either need to pick a specific loop implementation or pick interop and hope that gets settled sometime in the future. Creating our own event loop or standing still are not options we want to go with.

@kelunik How long will Amp wait for the spec? And are you aware of a timetable for a release?

**Comment by kelunik** [comment]
Amp will wait for the spec, no matter how long it takes. Amp v1 is stable, and we don't have any reason to release a v2 without interop being finalized.

The finalization of the spec depends entirely on the feedback and issues that arise.

**Comment by asm89** [comment]
@davidwdan Any issues with doing some bridging in RxPHP itself?

**Comment by kelunik** [comment]
@davidwdan Just a note for your first post: Icicle won't support the interop loop. Icicle will be discontinued and @trowski joins Amp for v2.

**Comment by davidwdan** [comment]
@asm89 As [pointed](https://github.com/WyriHaximus/reactphp-async-interop-loop/issues/6#issuecomment-268869873) out by @kelunik, the ReactPHP interop lib already provides that functionality, so I don't think that'll be necessary to handle any of that ourselves.

Do you have any recommendations on getting things to work with hhvm?

@kelunik first post updated

**Comment by asm89** [comment]
@davidwdan Ah, sorry now it clicks. TIL about the https://github.com/async-interop/event-loop initiative. That's quite exciting.

As for HHVM. What isn't working? Any loops based on `stream_select` should work. I recon it might be able to get something working with `async/await` as well. Not sure.

**Comment by davidwdan** [comment]
@asm89 I dug around a bit and it looks like all of the issues I was experiencing are fixed in nightly, except for `Throwable` type issues that I believe are related to this: https://github.com/facebook/hhvm/issues/7198

**Comment by martinsik** [comment]
@davidwdan I've noticed the automatic `bootstrap.php` was moved under `autoload-dev` directive so the loop doesn't start with `register_shutdown_function`. Should the v2 example from above now look like the following?

```
Loop::setFactory(ReactDriverFactory::createFactory());

\Rx\Observable::interval(1000)
    ->take(5)
    ->flatMap(function ($i) {
        return \Rx\Observable::of($i + 1);
    })
    ->subscribe(function ($e) {
        echo $e, PHP_EOL;
    });

Loop::get()->run();
```

Since RxJS 5 is officially released should RxPHP v2 try to mimic its functionality instead of RxJS 4? I'm asking because some operators already work like their RxJS 5 counterparts and this planned blocking variant of `forEach` comes from RxJS 5 as well (RxJS 4's `forEach` was just an alias to `subscribe`).

I know there are more differences between RxJS 4 and 5 such as `Subscriber`s instead of `Observer`s and basically just `CompositeDisposable` (`Subscription`) instead of all the different disposables. There're much more differences in its internals but these two are the most commonly referred on StackOverflow so I assume these are developers most likely to encounter.

I think many developers starting with RxPHP will already know RxJS 5 because of frontend frameworks such as Angular2 so they might be surprised that RxPHP v2 is somewhere between RxJS 4 and 5.

**Comment by davidwdan** [comment]
The demo code examples are also used on the reactivex.io website for documentation, so I wanted to remove as much of the boilerplate as possible.  Many of the v1 examples include a lot of loop code, which I think is messy and unnecessary for documentation purposes.

I'll update the quick start instructions, with the exact steps needed to run the demos, with some verbiage that explains how the demos are automatically run within ```Loop::execute```.

As far as compatibility with RxJS 4/5 goes, as long as we're close to those implementations, I think we'll be okay.  You would expect some inconsistencies, when moving from one language to another, and every other Rx implementation has some of its own variations on operators and schedulers.

**Comment by asm89** [comment]
@davidwdan Do you want to push the 2.x branch up to the main repository? It will make it easy to install and play around with!

**Comment by davidwdan** [comment]
@asm89 let me update the README and then I'll push it.  

Can you create a 2.0 ~~tag~~ label?

**Comment by asm89** [comment]
@davidwdan You should be able to do that yourself now. You could also make it a milestone?

So for now `master` will be 1.x and 2.x branch will be 2.x?

**Comment by asm89** [comment]
@davidwdan Anything left here? If yes, perhaps make separate issues for the `2.0` milestone?

Regarding branches, should we go for:
- current master -> `1.x`
- master = `2.x`?

**Comment by kelunik** [comment]
I can only strongly recommend not to release v2 with a non-final interop spec. We don't want to avoid BC breaks just because some library prematurely released a version using the specification.

**Comment by davidwdan** [comment]
@kelunik we are planning to wait for the final interop loop spec, before releasing v2.  However, if there are concerns with the stability of the interop loop, or if the final version isn't close to being released, we may have to release v2 with the old event loop scheduler and push interop support to v2.1

**Comment by davidwdan** [comment]
Most of the issues discussed here have been addressed or new issues have been opened, so I'm going to close this.
