### ISSUE TITLE
Demos and tests sometimes run with inconsistent results on travis

### ISSUE THREAD

**Issue by mbonneau** [ReactiveX/RxPHP#103]
As part of the tests on travis, RxPHP runs most of the demos to make sure they are still outputting the same expected results.

This is causing some flakiness in the tests as the demos use a real time clock to run and, given the asynchronous nature of Rx, sometimes the test environments get different results. (These are often cleared up by just rerunning the tests).

I opened this issue as a place to discuss possibilities for resolving this issue.

Example: #98

**Comment by asm89** [comment]
Do we know what other demos are affected? I'd just remove the `.expect` files for non deterministic demos if it's not easy to fix.

**Comment by mbonneau** [comment]
@asm89 - I don't have a record because travis does not keep the log when you rerun from what I can see. I will keep track so that we have some examples to look at before removing expect files.

**Comment by mbonneau** [comment]
I am going to close this issue as it does seem to be a case-by-case basis and can be corrected either by adjusting timing of the tests until they are deterministic or if it is truly non-deterministic, dropping the expect as suggested.
