### ISSUE TITLE
Setting in the static scheduler

### ISSUE THREAD

**Issue by mbonneau** [ReactiveX/RxPHP#114]
The static scheduler should not allow setting more than once.

The static scheduler also needs more testing.

**Comment by davidwdan** [comment]
For a couple of the operators I set the scheduler to [`Scheduler::getAsync()`](https://github.com/ReactiveX/RxPHP/blob/2.x/src/Observable.php#L149).  Since the default scheduler is the async, should those all be `Scheduler::getDefault()`?

**Comment by mbonneau** [comment]
That should use the default, and then if someone ever mixes timed operators after they set default to immediate, they will just an exception explaining that they can't do that.

**Comment by davidwdan** [comment]
I agree, but I'm talking about when we pass a scheduler to the operators.  Should they all be `Scheduler::getDefault()`?

**Comment by mbonneau** [comment]
Is there really such a thing as default? Maybe we should drop default and use `getAsync`?
