### ISSUE TITLE
How to use the demos?

### ISSUE THREAD

**Issue by geoidesic** [ReactiveX/RxPHP#152]
This may be a stupid question – but what exactly am I supposed to get from the demos?
Each demo contains two files... loading each in the browser gives the same static result.
I'm left just feeling bemused. There's little documentation and the demo's shed no light for me at all on what this all is nor how to make use of it.

**Comment by geoidesic** [comment]
There's also a docs folder but browsing to any of those just shows a blank page.

**Comment by davidwdan** [comment]
@geoidesic If you run `php demo/average/average.php` from the cli, the output will match `demo/average/average.php.expect`

The doc folder is there for auto doc generation for http://reactivex.io/documentation/operators.html, which is also where you can find more documentation.
