### ISSUE TITLE
Returning a custom Observable from a custom operator

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/RxPHP#160]
The `Observable::__call` method internally uses the `lift()` method which means all custom operators always return an instance of `AnonymousObservable`.

I'm thinking how could I implement a custom operator returning a different Observable. For example I want to implement `publishWhatever()` which should return an instance of `ConnectableObservable`.

Maybe operators that don't want to use `lift()` could implement some interface and the `__call` method will behave accordingly?

**Comment by davidwdan** [comment]
@martinsik That's a good point.

This might not be exactly what you're looking for, but you can use `compose` to do something similar:

```PHP
$publishWhatever = function (Observable $source) {
    //Do stuff
    return new Observable\ConnectableObservable($source);
};

$s = Observable::interval(1000)->compose($publishWhatever);

$s->subscribe('print_r');

$s->connect();
```

**Comment by martinsik** [comment]
@davidwdan This is a good workaround for now.

Nonetheless it would be nice to have this covered by the `__call()` method itself.
