### ISSUE TITLE
`forkJoin` does not work as I expected

### ISSUE THREAD

**Issue by CedX** [ReactiveX/RxPHP#176]
Using RxPHP version 2.0.2 with PHP 7.1.7 (on Windows 10, on OSX El Capitan and on Ubuntu 17.04). The behavior is the same on every platform, with an immediate scheduler or with the React event loop.

When I try to run the `forkJoin` demo :

```shell
$ php forkJoin.php
Next value: 47c
Complete!
````

But when looking at the code, the next value should be: `45c` (e.g. the `7` value is not the last one produced by `$obs2`... in fact `7` is not produced at all by any observable).

```php
$obs1 = Observable::range(1, 4);
$obs2 = Observable::range(3, 5);
$obs3 = Observable::fromArray(['a', 'b', 'c']);
```

When using `forkJoin` in my own code :

```php
$obs1 = <an observable that produces a single `Job` instance>;
$obs2 = <an observable that produces a single `Configuration` instance>;
$obs3 = <an observable that produces a single `GitData` instance>;

Observable::forkjoin([$obs1, $obs2, $obs3], function($v1, $v2, $v3) {
  echo '$v1 = ', get_class($v1), PHP_EOL;
  echo '$v2 = ', get_class($v2), PHP_EOL;
  echo '$v3 = ', get_class($v3), PHP_EOL;
})->subscribe(...);
```

The output I get is not in the expected order (and it is the same even if I change the scheduler):

```shell
$v1 = Configuration
$v2 = Job
$v3 = GitData
```

I'm starting with the Observables: have I misinterpreted what `forkJoin` should produce, have I missed something? Thanks in advance.

**Comment by davidwdan** [comment]
The signature for `range` is `Observable::range($start, $count)`, not `$start, $end` like the PHP range function, so `7` is the last value emitted by the second observable. 

Can you provide a working code example of the ordering issue?  It should maintain the order of the observables passed into forkJoin.

**Comment by CedX** [comment]
Oh my bad! (e.g. "$start, $count", instead of "$start, $end"). Thanks for this remark.

A "working" code? Not really.
But my issue raised when I worked on this code (e.g. the code is still in development and unstable): https://github.com/cedx/coveralls.php/blob/develop/lib/Client.php#L141

(ignore the previous `return` statement with `mergeAll/toArray` : a previous trial before opting for `forkJoin`)

Some details from the CI:
https://travis-ci.org/cedx/coveralls.php/builds/255457005#L362

I still have numerous issues at creating such code: Observables need good programmers and brains... which I lack ;)

**Comment by CedX** [comment]
Hmmm... still no luck with the `forkJoin` API (whatever I do, I'm still getting the results in the wrong order... or at least not in the order that I expected).

But, replacing `Observable::forkJoin($observables)` by `Observable::fromArray($observables)->concatAll()->toArray()` solved the issue (even if the semantics are not the same...). Using `mergeAll` instead of `concatAll` gave me the same order as `forkJoin`.

I still haven't found any clue why `forkJoin` does not produce the expected output with my code :(

Another (off topic?) question: how could I replace the `forkJoin` call by a `zip` one? In RxJS, I used to use the `Observable.zip()` static method instead of the `forkJoin` one... but I don't know how to do the same with RxPHP where `zip` is an instance method.

Using `Observable::empty()->zip($observables)` does not produce any "next" event... so the `zip` method does not produce any value. 

(sorry to bother you with all my questions, but RX is hard to learn and it's a bit difficult to try to transpose the RxJS API in terms of RxPHP API)

**Comment by mbonneau** [comment]
For the `zip` question: rxjs `Observable.zip(o1, o2, o3)` would need to be `$o1->zip([$o2, $o3])`

**Comment by mbonneau** [comment]
@cedx - For what you describe above, I usually use `combineLatest` or `withLatestFrom`.

**Comment by CedX** [comment]
@mbonneau Thanks!

Basically, what I'm trying to achieve is more or less the same behavior as `Promise.all()` in JavaScript... and the choice is open: `combineLatest`, `forkJoin`, `zip`... Thanks to [this article](https://www.bennadel.com/blog/3192-performing-the-stream-equivalent-of-promise-all-using-rxjs.htm), I finally opted for `zip` in my RxJS code.

I should really look closer at the RxPHP demos : the `zip` one is pretty self-explanatory. [Replacing `forkJoin`/`concatMap->toArray` by `zip`](https://github.com/cedx/coveralls.php/blob/master/lib/Client.php#L114) finally resolved my issue in a way that suits me :)

I close this ticket, thanks guys.

**Comment by davidwdan** [comment]
@cedx I finally got a chance to look at your code.  You should be able to simplify https://github.com/cedx/coveralls.php/blob/develop/lib/Client.php#L105-L111 to:
```PHP
      which('git')
          ->flatMapTo(GitData::fromRepository())
          ->catch(function (): Observable {
              return Observable::empty();
          })
          ->defaultIfEmpty(Observable::of(null))
```
