### ISSUE TITLE
Change behavior when exception occurs in `onNext`

### ISSUE THREAD

**Issue by mbonneau** [ReactiveX/RxPHP#192]
Right now if there is an exception in the `onNext` handler, it is possible that errors and exceptions get swallowed inside the library (or a promise from some other library).

The plan is to catch these and send them down the `onError` handler so that the user can see the problem.

Also, a default `onError` handler should be added that will log an error with the error information. This will help if users do not set the `onError` handler.

**Comment by davidwdan** [comment]
Here is a discussion about RxJS, which suffers from the same issue:
https://github.com/ReactiveX/rxjs/issues/2813
