### ISSUE TITLE
How to resume on next after catch?

### ISSUE THREAD

**Issue by Sevavietl** [ReactiveX/RxPHP#199]
Thank you for the great library.

I see that `catch` method is available on `Observable`. I cannot figure out how to resume after catching an error (exception). From the [ReactiveX documentation](http://reactivex.io/documentation/operators/catch.html) I see that for some languages this functionality is implemented (if I am not mistaken). Please, advice me how resume on next can be done in PHP?

Thank you in advance.

**Comment by Sevavietl** [comment]
Oh, I guess I can use `retryWhen` for this ([docs](http://reactivex.io/documentation/operators/retry.html)). 

Just another question. Say I have `bufferWithCount` to deal with backpressure (I use [amp/mysql](https://github.com/amphp/mysql) to select records from the database and it selects rows much quicker then they are processed). After that I `flatMap` the buffer portion with `Observable::fromArray`. Later on I can have an exception during record processing. When I use `retryWhen` will the stream continue with a new buffer portion (from the begining of the observable) or with the next item in the current portion?

Thank you in advance.

Sorry for polluting your issues.

**Comment by mbonneau** [comment]
It may be easier to understand what you are trying to do if you get a little code example for us.

If you want to survive errors on individual items, you would need to `catch` on the observable that is returned in the `flatMap` function.

**Comment by davidwdan** [comment]
Closing since there hasn't been an update in a while
