### ISSUE TITLE
Test not working

### ISSUE THREAD

**Issue by factormaarten** [ReactiveX/RxPHP#201]
Hi there,

I'm trying to test observables in PHPUnit, however I get stuck.

I have looked at the tests in this repo, even copied one of them directly, yet it fails.

```
Failed asserting that null matches expected 42.
```

When trying this code

```php
$promise = Observable::of(42)->toPromise();

        $result = null;
        
        $promise->then(function ($value) use (&$result) {
            $result = $value;
        });
        
        $this->assertEquals(42, $result);
```

How do I solve this?

**Comment by mbonneau** [comment]
I suspect the issue you are having has to do with the scheduler. This library generally works asynchronously, so the `Observable::of(42)` just schedules the emission of a value and does not emit a value unit the underlying scheduler is run. This means the `then` callable does not get called until after your assertion is made (again, assuming the scheduler is started at some point).

If you wanted it to work immediately, you can use the `ImmediateScheduler`:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$promise = \Rx\Observable::of(42, new \Rx\Scheduler\ImmediateScheduler())->toPromise();

$result = null;

$promise->then(function ($value) use (&$result) {
    $result = $value;
});

echo $result . PHP_EOL;
```
This can also be set with the global configuration:
```php
\Rx\Scheduler::setDefaultFactory(function () {
    return new \Rx\Scheduler\ImmediateScheduler();
});

$promise = \Rx\Observable::of(42)->toPromise();
```
Or, if you are intending to be async, you could defer checking the result until the after the value is emitted.

**Comment by mbonneau** [comment]
@mpjraaij I just saw your comment on https://github.com/voryx/PgAsync. If you are using this in conjunction with that, you do not want to use the `ImmediateScheduler`.
