### ISSUE TITLE
When trying to write a test I get 'Error: Call to undefined function Tests\onNext()'

### ISSUE THREAD

**Issue by factormaarten** [ReactiveX/RxPHP#204]
Hi,

I'm trying to write a test for an observable in my code. In there I have this code:

```
$observable = new HotObservable(
            $scheduler,
            [
                onNext('foo'),
                onNext('bar')
            ]
        );
```

Unfortunately this gives the error that onNext does not exist.

How do I solve this?

**Comment by davidwdan** [comment]
Make sure that you're loading the test helper functions in composer:
https://github.com/ReactiveX/RxPHP/blob/master/composer.json#L38-L41
