### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by sukei** [ReactiveX/RxPHP#207]
Hello,

Is there any plan to bump the PHP requirements to allow PHP 8?

**Comment by mbonneau** [comment]
Yes. I don't have a timetable of when this is going to happen, but I would like to get this done soon.

**Comment by mbonneau** [comment]
See #208

**Comment by mbonneau** [comment]
@sukei RxPHP v 2.0.8 has been released - enjoy.

**Comment by sukei** [comment]
Thank you guys!
