### ISSUE TITLE
Deprecate ImmediateScheduler?

### ISSUE THREAD

**Issue by asm89** [ReactiveX/RxPHP#32]
It seems that the ImmediateScheduler is causing us a bunch of problems. It doesn't actually schedule anything, but just calls the scheduled action directly. This occasionally blows out the stack and some operators won't work at all.

The ImmediateScheduler mostly seems to exist because it was easy to run small demos with it when the project was still young. It's unusable for anything serious. Should we:
- deprecate the scheduler (we can one day remove it in a `2.x`)
- optionally add a simple trampolining scheduler and make that the default (without any fancy I/O stuff, if you want that then use the reactphp one)

Thoughts @cboden @davidwdan @mbonneau @ocramius?

**Comment by Ocramius** [comment]
> This occasionally blows out the stack

With XDebug or just infinite stack => segfault?

> some operators won't work at all.

Is there an example, or a reference of this?

> The ImmediateScheduler mostly seems to exist because it was easy to run small demos with it when the project was still young. It's unusable for anything serious. Should we:

Those small demos are still kinda required. What is the alternative approach?

**Comment by davidwdan** [comment]
Here's an example that will give the wrong output and then segfault:

``` php
$o1 = Rx\Observable::just(42)->repeat();
$o2 = Rx\Observable::just(21)->repeat();

$mergedObservable = $o1
    ->merge($o2)
    ->take(10);
```

output:

```
Next value: 42
Next value: 42
Next value: 42
Next value: 42
Next value: 42
Next value: 42
Next value: 42
Next value: 42
Next value: 42
Next value: 42
Complete!
[1]    59785 segmentation fault ...

```

expected output:

```
Next value: 42
Next value: 21
Next value: 42
Next value: 21
Next value: 42
Next value: 21
Next value: 42
Next value: 21
Next value: 42
Next value: 21
Complete!
```

**Comment by mbonneau** [comment]
As I see it - the pros and cons of the ImmediateScheduler are:

Pros:
- Can write simple demos for some of the operators.
- Requires no boilerplate code for the things that work with it.
- You don't need an event loop.

Cons:
- Most test cases use a scheduler that actually schedules items, so almost all test cases are not valid for the ImmediateScheduler.
- Execution ordering can be different with the ImmediateScheduler than with others.
- ImmediateScheduler has a tendency to blow the stack.
- Cannot do anything that requires timing (interval, timeout, delay, etc.).

I would prefer that we move away from the ImmediateScheduler. This would mean that the barrier to entry would be a tiny bit higher in that people will at the very minimum need to start a loop or scheduler (unless we make a scheduler that autostarts either on subscribe or at the end of execution).

It is possible to make a really simple scheduler that just uses sleep if we wanted the bare minimum scheduler - but that would still require a start.

**Comment by davidwdan** [comment]
I'm going to close this issue.  Even if you default to an async scheduler, we'll still need the immediate scheduler for some functional tests.
