### ISSUE TITLE
Rx\React\Promise::toObservable allows reject to pass non-exceptions to onError

### ISSUE THREAD

**Issue by mbonneau** [ReactiveX/RxPHP#33]
https://github.com/ReactiveX/RxPHP/blob/40edc235ff964e9d035148074a2a48e0eec15e82/lib/Rx/React/Promise.php#L79

There should be something to stop non-exceptions from being passed through to onError.

A behavior for when this happens would need to be worked out - maybe create a Rx\React\RejectedPromiseException that could hold the non-exception value?

**Comment by asm89** [comment]
@mbonneau Doesn't react enforce the error to be an exception? :/

**Comment by asm89** [comment]
I guess not. In that case wrapping it probably makes sense.
