### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by alexsup** [ReactiveX/RxPHP#35]
Not an issue, more a question but could you point me in the direction of how to test something like the following:

$observable
->flatmap(function($value){
    return a zip of a couple of api requests if exists
})
->map(function($value){
    return a cleaned value
})
->flatmap(function($value){
    return related api requests if exists
})
->filter(function($value){
    return false if related api requests don't pass
})
->filter(function($value){
    return false if related api requests don't pass
})
->filter(function($value){
    return false if related api requests don't pass
})
->toArray();

Thanks!

P.S thanks for an awesome library :)

**Comment by mbonneau** [comment]
@alexsup - To clarify the question, you are asking how to do a unit test of something like this?

``` php
class MyClass {
    public function someMethod(Rx\Observable $observable)
    {
        return $observable
            ->flatmap(function($value){
                return \Rx\Observable::emptyObservable()->zip(
                    \Rx\React\Http::get("http://www.example.com/" . $value),
                    \Rx\React\Http::get("http://www.example2.com/" . $value)
                );
            })
            ->map(function ($value) {
                return cleaned($value);
            })
            ->flatmap(function ($value) {
                return someOtherFunctionThatReturnsAnObservable($value);
            })
            ->filter(function ($value) {
                return is_good_value($value);
            })
            ->toArray();
    }
}
```

**Comment by alexsup** [comment]
@mbonneau Yes. The injected $observable is an ArrayObservable in this case.

So, based on your suggestion, you perhaps wouldn't test the output of the operators but rather simply test abstracted methods as you would in non-Rx code?

If, so then how would do integration testing on all the operators?

For example, if I created an Observable with `new \Rx\Observable\ArrayObservable($arrayOfIds, $scheduler);`, how would I test an expected outcome based on onNext or onCompleted

Thanks!

**Comment by mbonneau** [comment]
This is a very good question. I can only give suggestions on this topic as I don't know what the "right" way is.

In the example I included above, there are some pretty horrible things going on from a testability standpoint. The Http::gets are reaching outside of not only the `flatMap` selector but completely outside of everything. This makes it nearly impossible to mock for unit testing.

For this example, there are a few different ideas.

You could use separate methods for the selectors that are getting outside information:

``` php
class MyClass {
    public function httpGetAndZip($value)
    {
        return \Rx\Observable::emptyObservable()->zip(
            \Rx\React\Http::get("http://www.example.com/" . $value),
            \Rx\React\Http::get("http://www.example2.com/" . $value)
        );
    }

    public function myOtherFunctionThatReturnsAnObservable($value)
    {
        return new SomeOtherObservable($value);
    }

    public function someMethod(Rx\Observable $observable)
    {
        return $observable
            ->flatmap([$this, 'httpGetAndZip'])
            ->map(function ($value) {
                return $value[0] + $value[1]; // simplified for this example
            })
            ->flatmap([$this, 'myOtherFunctionThatReturnsAnObservable'])
            ->filter(function ($value) {
                return true;  // simplified for this example
            })
            ->toArray();
    }
}
```

This would allow you to mock the two problematic selectors using PHPUnit like this:

``` php
class MyClassTest extends PHPUnit_Framework_TestCase
{
    public function testSomeMethod()
    {
        $myClass = $this->getMockBuilder(MyClass::class)
            ->setMethods(["httpGetAndZip", "myOtherFunctionThatReturnsAnObservable"])
            ->getMock();

        $myClass->expects($this->exactly(3))
            ->method('httpGetAndZip')
            ->withConsecutive(
                [$this->equalTo(1)],
                [$this->equalTo(2)],
                [$this->equalTo(3)]
            )
            ->willReturnOnConsecutiveCalls(
                \Rx\Observable::just([1,1]),
                \Rx\Observable::just([2,2]),
                \Rx\Observable::just([3,3])
            );

        $myClass->expects($this->exactly(3))
            ->method("myOtherFunctionThatReturnsAnObservable")
            ->withConsecutive(
                [$this->equalTo(2)],
                [$this->equalTo(4)],
                [$this->equalTo(6)]
            )
            ->willReturnOnConsecutiveCalls(
                \Rx\Observable::just("a"),
                \Rx\Observable::just("b"),
                \Rx\Observable::just("c")
            );

        $scheduler = new \Rx\Testing\TestScheduler();

        $returnedObservable = $myClass->someMethod(\Rx\Observable::fromArray([1, 2, 3]));

        $returnedValue = null;
        $completes = false;

        $returnedObservable->subscribeCallback(
            function ($x) use (&$returnedValue) {
                $returnedValue = $x;
            },
            [$this, 'fail'], // fail the test if there is any errors
            function () use (&$completes, &$returnedValue) {
                $this->assertNotNull($returnedValue);
                $completes = true;
            }
        );

        $scheduler->start();

        $this->assertTrue($completes);
        $this->assertEquals(["a", "b", "c"], $returnedValue);
    }
}
```

which leaves you not only with complete control over the methods, but also lets you validate what it going into them. (The TestScheduler is used in this example just so that we are using a real scheduler - not the ImmediateScheduler).

Another option might be to pass the selectors into `someMethod` which would allow you to replace them during testing.

Please let me know if this helps.

**Comment by asm89** [comment]
If something like this is the actual structure you have:

```
            ->map(function ($value) {
                return cleaned($value);
            })
            ->flatmap(function ($value) {
                return someOtherFunctionThatReturnsAnObservable($value);
            })
            ->filter(function ($value) {
                return is_good_value($value);
            })
```

I'd (unit) test the `cleaned()` method etc in isolation and probably have some integration test on top of that.

**Comment by alexsup** [comment]
@mbonneau Brilliant thank you! I'll investigate today :)

@asm89 Thanks also!

One more question and I'll leave you in peace!

What's the best process for sub scheduling? 

For example, in the following example:

```
->flatMap(function ($value) {
    return fetchHttpGetFromId($value);
})
->flatMap(function ($value) {
    return fetchTwentyRelatedHttpGetFromValue($value);
})
```

Say I start with an ArrayObservable of 20 unique urls on a scheduler as so:

```
$loop = \EventLoop\getLoop();
$scheduler = new Rx\Scheduler\EventLoopScheduler($loop);
$observable = new Rx\Observable\ArrayObservable($users, $scheduler);
```

The initial flatMap runs async (i.e. for each unique URI) but the second flatMap doesn't.

What is the best method to trigger async requests in the second flatMap?

Thank you!

**Comment by mbonneau** [comment]
Ideally everything should be async. Are you wanting them to run synchronously?

**Comment by alexsup** [comment]
Not intentionally... But then I am new to this!

Perhaps, I should be more specific. This is the operator chain:

```
        $ids = ["array","of","100","ids"];

        $loop = \EventLoop\getLoop();

        $scheduler = new \Rx\Scheduler\EventLoopScheduler($loop);

        $observable = new \Rx\Observable\ArrayObservable($ids->toArray(), $scheduler);

        $allTheObservables = $observable

            ->flatMap(function ($value) {

                $user = \Rx\React\Http::get($uri.$value));

                $meta = \Rx\React\Http::get($uriTwo.$value);

                $return $user->zip([$meta], function($user, $meta){

                    return ['user'=>$user,'meta'=>$meta];
                });

            },$scheduler)

            ->filter(function($value) {

                if(empty($value['meta']['twentyRelatedUris']))
                {
                    return false;
                }

                return true;
            })

            ->flatMap(function($value) {

                $relatedURIs = $value['meta']['twentyRelatedUris'];

                return new \Rx\Observable\ArrayObservable($relatedURIs);

            },$scheduler)

            ->flatMap(function($value) {

                $id = $value['id'];

                $relatedUri = \Rx\React\Http::get($uri.$id));

                $meta = \Rx\React\Http::get($uriTwo.$id);

                $return $relatedUri->zip([$meta], function($relatedUri, $meta) use ($value) {

                    return ['user'=>$user,'meta'=>$meta,'origonalUri'=>$value];

                });

            },$scheduler)

            ->filter(function($value) {

               if($value['origonalUri']['param'] != $value['user']['param'])
               {
                    return false;
               }

               return true;

            },$scheduler)

            ->toArray();

        // Subscribe
        $allTheObservables->subscribe($callbackObserver(), $scheduler);
```

From where I  am returning `new \Rx\Observable\ArrayObservable($relatedURIs);` onwards, each of those ArrayObservables are running synchronously.

Ideally, I would like each of the 100 uris to run async (as it is) and then their twenty related uris to run async inside the original streams.

Thank you!

**Comment by davidwdan** [comment]
@alexsup how do you know it's running synchronously after returning the ArrayObservable?

**Comment by alexsup** [comment]
@davidwdan if I dump the uri at each stage, the first flatMap prints 100 at once within less than a second.

The second flatmap dumps the uri every 200/300ms or so one after the other.

So it's my assumption that they are not synchronous.

Do I need to create new schedulers for the second ArrayObservable?

Thanks!

**Comment by asm89** [comment]
You don't pass the the scheduler to the first `filter()` perhaps that's where it goes haywire?

We should finish and ship https://github.com/ReactiveX/RxPHP/pull/25. Then you'd only set up a scheduler once and not even explicitly pass it for most cases.

**Comment by davidwdan** [comment]
`filter()` doesn't take a scheduler as an argument, neither does `ArrayObservable`.  The scheduler you pass to subscribe will pretty much be used everywhere, so everything should be async.

While looking into this, we did find an issue with the `EventLoopScheduler`, but I think that may be unrelated. see https://github.com/ReactiveX/RxPHP/issues/36

**Comment by alexsup** [comment]
I created a much simpler operator flow that replicates the synchronicity issue:

```
$startTime = microtime(true);

$loop = \EventLoop\getLoop();

$scheduler = new Rx\Scheduler\EventLoopScheduler($loop);

$observable = new Rx\Observable\ArrayObservable(range(1, 10), $scheduler);

$selectManyObservable = $observable

    ->flatMap(function($value) {
        return  \Rx\React\Http::get("https://publicdata-airports.firebaseio.com/.json");

    }, $scheduler)

    ->flatMap(function($value) {
        $nodes = json_decode($value);

        $relatedNodes = [];
        foreach($nodes as $key => $node)
        {
            $relatedNodes[] = $key;
        }

        return new Rx\Observable\ArrayObservable($relatedNodes);

    }, $scheduler)

    ->flatMap(function($value){
        return \Rx\React\Http::get("https://publicdata-airports.firebaseio.com/{$value}.json");
    },$scheduler)


    ->map(function($value) use($startTime) {
        return microtime(true) - $startTime;
    },$scheduler);


$disposable = $selectManyObservable->subscribe($stdoutObserver, $scheduler);

$loop->run();
```

**Comment by davidwdan** [comment]
@alexsup Can you update to the latest version of RxHttp and then run the following example?  You should see indexes and airports come in out of order.

``` php

$loop       = \EventLoop\getLoop();
$scheduler  = new Rx\Scheduler\EventLoopScheduler($loop);

$observable = \Rx\Observable::range(1, 2);

$selectManyObservable = $observable
    ->flatMap(function ($value) {
        return \Rx\React\Http::get("https://publicdata-airports.firebaseio.com/.json");
    })
    ->map('json_decode')
    ->flatMap(function ($nodes) {
        $relatedNodes = array_keys((array)$nodes);

        return Rx\Observable::fromArray($relatedNodes);
    })
    ->filter(function ($airportCode) {
        return $airportCode[0] !== '_';
    })
    ->mapWithIndex(function ($i, $value) {
        return [$i, $value];
    })
    ->flatMap(function (array $values) {
        return \Rx\React\Http::get("https://publicdata-airports.firebaseio.com/{$values[1]}.json")
            ->map(function ($x) use ($values) {
                return [$values[0], $x];
            });
    })
    ->map(function (array $x) {
        $index = $x[0];
        $x     = json_decode($x[1]);
        return "Temperature at " . $x->IATA . ": " . $x->weather->temp . " (from index $index)";
    });

$disposable = $selectManyObservable->subscribe(new \Rx\Observer\CallbackObserver(
    function ($x) {
        echo $x, PHP_EOL;
    }
), $scheduler);

```

Output:

```
Temperature at BNA: 59.0 F (15.0 C) (from index 1)
Temperature at BOS: 43.0 F (6.1 C) (from index 2)
Temperature at ATL: 75.0 F (23.9 C) (from index 0)
Temperature at BWI: 67.0 F (19.4 C) (from index 3)
Temperature at CLE: 37.0 F (2.8 C) (from index 4)
Temperature at ATL: 75.0 F (23.9 C) (from index 6)
Temperature at CVG: 53.0 F (11.7 C) (from index 7)
Temperature at PDX: 43.0 F (6.1 C) (from index 49)
...
```

```
```

**Comment by alexsup** [comment]
@davidwdan Total success, thank you! :+1: 

By removing the scheduler out of the operators and updating RxHttp, it all work super fast.

Out of interest, the demo of flatMap passes the scheduler into the Array Observable yet that didn't work for me.

Under what circumstances should we pass schedulers and when shouldn't we?

Incidentally, we're putting together a our own noobs guide to RX (we're also using RX Swift) mainly to help us get our head round it and share with others on our team. Apart from http://reactivex.io/, where do you recommend I go to really understand how reactive works.

I feel the questions I'm asking are pretty basic and If I really want to know more about how reactive works as I'm totally sold :)

Thanks again for your help!

Alex

**Comment by davidwdan** [comment]
@alexsup Thanks for pointing out the issue with the flatMap demo.  

If you're using any time based operators or have streams that emit concurrently, you'll need to use the EventLoopScheduler. Time based operators take a scheduler as an argument or you can pass the scheduler into subscribe, which will override the default ImmediateScheduler for all operators in the chain.

RxPHP is basically a port of RxJS, so any of those examples that you find can be applied.  Egghead has some good RxJS videos here: https://egghead.io/technologies/rx

**Comment by alexsup** [comment]
@davidwdan perfect, thank you!

@mbonneau Thanks for the testing advice -> all green :)
