### ISSUE TITLE
Memory leak on scheduler

### ISSUE THREAD

**Issue by Vinceveve** [ReactiveX/RxPHP#61]
Hi, thanks a lot for this initiative.

``` php
$loop = Factory::create();
$scheduler = new EventLoopScheduler($loop);

$mem = function() {
    echo memory_get_usage(true)."\n";
};

$scheduler->schedulePeriodic($mem, 0, 100);

\Rx\Observable::interval(100, $scheduler)
    ->subscribeCallback($mem);

$loop->run();
```

Whatever method I take I get a bump of 3Mb of memory every 5s.
With `$loop->addPeriodicTimer` everything is stable.

**Comment by davidwdan** [comment]
@Vinceveve Does the memory usage continue going up until it runs out of memory or does it level off after a little bit?

What happens if you add `gc_collect_cycles()` to your `$mem` function?

**Comment by Vinceveve** [comment]
@davidwdan My bad it's garbage collector 
After 10mn it stacks at 8Mb without gc, With GC cleaning it stays at 5mb in the first 10s.

Thank you :)
