### ISSUE TITLE
Errors in max.php.expect

### ISSUE THREAD

**Issue by rjhdby** [ReactiveX/RxPHP#62]
max.php

```
max([1, 3, 5, 7, 9, 2, 4, 6, 8]) == 9 !?

<?php
require_once __DIR__ . "/../bootstrap.php";
/* Without comparer */
$source = \Rx\Observable::fromArray([1, 3, 5, 7, 9, 2, 4, 6, 8])
    ->max();
$subscription = $source->subscribe($createStdoutObserver());
```

max.php.expect

```
Next value: 9
Complete!
```

**Comment by davidwdan** [comment]
@rjhdby what is the error?

**Comment by rjhdby** [comment]
@davidwdan 
max from [1, 3, 5, 7, 9, 2, 4, 6, 8] is 8, not 9

It's has misled me. I had spent some time for review code for understanding what it is mistake in max.php.expect, but not in code.

**Comment by davidwdan** [comment]
@rjhdby the max from [1, 3, 5, 7, **9**, 2, 4, 6, 8] is 9.  Those numbers are not sequential.

**Comment by rjhdby** [comment]
shame on my head. Sorry. :)

**Comment by davidwdan** [comment]
:smile: Nothing to be sorry for.  I'm going to close this issue
