### ISSUE TITLE
travis-ci fails because of "throttle.php" demo

### ISSUE THREAD

**Issue by martinsik** [ReactiveX/RxPHP#98]
For some reason the demo with [`[x] demo/throttle/throttle.php`](https://travis-ci.org/ReactiveX/RxPHP/jobs/181767944#L421) fails and marks the build as failed.

When I ran the same tests locally on PHP 7.0.13 and PHP 5.6.25 it sometimes passes and sometimes fails. So maybe something with the order of events?

**Comment by martinsik** [comment]
I just tested it a little and it returns one of these two results:

```
$ for i in {1..10}; do php7 demo/throttle/throttle.php; done
```
```
Next value: 0
Next value: 2
Next value: 1
Next value: 3
Complete!
Next value: 0
Next value: 4
Next value: 1
Next value: 3
Complete!
```

The correct one is:
```
Next value: 0
Next value: 2
Next value: 1
Next value: 3
Complete!
```

So numbers `2` and `4` are sometimes interchanged.

**Comment by mbonneau** [comment]
@martinsik - The demos and their intermittent failure on tests due to timing issues is something I have been wrestling with.  As for the `throttle` demo, I was able to work out the timing issue by changing the times to give a little more breathing room, but hhvm is now causing issues with not completing. I have not been able to dig too deeply into that because I don't have an easily available hhvm debug environment setup.

I would like to get the "failing" badge off the page soon, but I want to find the best solution to this testing issue without just skipping some of the demos.

**Comment by martinsik** [comment]
@mbonneau I spent some time trying to debunk this.

I went through the demo `thorttle.php` and `ThrottleTest.php` again step by step with debugger to see what's going on and I think the order or events is different to what I thought at the beginning.

The input is following:

    ['value' => 0, 'time' => 100],
    ['value' => 1, 'time' => 600],
    ['value' => 2, 'time' => 400],
    ['value' => 3, 'time' => 900],
    ['value' => 4, 'time' => 200]

This is that should happen with a real-time Scheduler (eg. `EventLoopScheduler`):
```
time [value] = event
100 [0] = "Next value: 0", nextSend = 399
200 [4] = Add timer to fire at 399
399 [4] = "Next value: 4", nextSend = 698
400 [2] = Add timer to fire at 698
600 [1] = Add timer to fire at 698 (disposes previous subscription)
698 [1] = "Next value: 1", nextSend = 997
900 [3] = Add timer to fire at 997
997 [3] = "Next value: 3"
```
That `-1` is caused when [calculating `$this->nextSend`](https://github.com/ReactiveX/RxPHP/blob/master/lib/Rx/Operator/ThrottleOperator.php#L57). This is also assuming there's no overhead so all times are set precisely.

The order is then:
```
Next value: 0
Next value: 4
Next value: 1
Next value: 3
```

However with `TestScheduler` the behavior is different:

```
time [value] = event
100 [0] = "Next value: 0", nextSend = 399
200 [4] = Add timer to fire at 399
`ReturnObservable` calls `$scheduler->schedule(...)` and makes `$dueTime = $this->clock + 1`
This makes the event scheduled to 400
400 [2] = "Next value: 2", nextSend = 699
400 [4] = Add timer to fire at 699 (because of `ReturnObservable` it's scheduled at 700)
600 [1] = Add timer to fire at 699 (disposes previous subscription, because of `ReturnObservable` it's scheduled at 700)
700 [1] = "Next value: 1", nextSend = 999
900 [3] = Add timer to fire at 999 (because of `ReturnObservable` it's scheduled at 1000)
1000 [3] = "Next value: 3"
```
The order is then:
```
Next value: 0
Next value: 2
Next value: 1
Next value: 3
```

Since `VirtualTimeScheduler` uses custom `PriorityQueue` where events with the same priority are executed in the order they were added we receive `2` instead of `4`. The `+1` is happening in the [`TestScheduler`](https://github.com/ReactiveX/RxPHP/blob/master/lib/Rx/Testing/TestScheduler.php#L24).

The following test case simulates the example above and is passing:

    public function throttle_event_scheduled_at_the_same_time()
    {
        $xs = $this->createHotObservable([
            onNext(100, 0),
            onNext(600, 1),
            onNext(400, 2),
            onNext(900, 3),
            onNext(200, 4),
            onCompleted(900)
        ]);

        $results = $this->scheduler->startWithTiming(function () use ($xs) {
            return $xs->throttle(300);
        }, 0, 1, 1500);

        $this->assertMessages([
            onNext(100, 0),
            onNext(400, 2),
            onNext(700, 1),
            onNext(1000, 3),
            onCompleted(1000)
        ], $results->getMessages());
    }

So I think the question is what should happen when two event are scheduled to exactly the same time like in the examples above numbers `2` and `4` should run at time `400`. Which of these two should run first, the one added first? The current custom comparer in `PriorityQueue` prefers the one first added (if I'm not mistaken).

I thought the `-1`s were to ensure that the delayed event will be run before another eventual event scheduled on the same time. Now I'm confused and maybe it was meant to compensate the `ReturnObservable`?

The inconsistent order with `thorttle.php` is probably because of the overhead and therefore inaccurate timing when adding events to the Scheduler. I saw that `DelayOperator` tries to timestamp the event and calculate the difference when scheduling an event but I guess milliseconds aren't accurate enough so sometimes the events happen in different order.

I also tried an alternative implementation without `DelayOperator` and without `-1` that shouldn't cause such overhead (this is just the inner subscription):

```
$now = $scheduler->now();

if ($this->nextSend <= $now) {
    $innerDisp->setDisposable(new EmptyDisposable());
    $observer->onNext($x);
     $this->nextSend = $now + $this->throttleTime;
     return;
}

$newDisp = $scheduler->schedule(function() use ($x, $observer, $scheduler) {
    $observer->onNext($x);
    $this->nextSend = $scheduler->now() + $this->throttleTime;
    if ($this->completed) {
        $observer->onCompleted();
    }
}, $this->nextSend - $scheduler->now());
```

With this all tests are passing but obviously the inconsistent behavior with `throttle.php` remains. 

if I give it more time space with `-1` it runs consistently with `0, 4, 1, 3` which is expected behavior if my assumption at the beginning was correct.

The tests are of course failing (there's `-1` difference in timing) and I don't know if this is even a good approach because when expecting the internal overhead to be max `1ms` it will probably never be 100% reliable. Should RxPHP even guarantee consistent order of event in these situations?

So the question at this moment what is the expected behavior from `ThrottleOperator` :).

**Comment by davidwdan** [comment]
The throttle example uses `EventLoopScheduler`, which is asynchronous, so it does not guarantee that events will happen in order.

The `return Observable::just($item['value'])->delay($item['time'])` in the example, would most likely be something like`PHP return Http::get('http://example.com')` in real life, which would not return in order.

**Comment by martinsik** [comment]
So the demo should be updated (just change emission times) to produce consistent results and this overlapping of emissions is an edge case that RxPHP can't resolve.

**Comment by martinsik** [comment]
I sent a PR with updated `throttle.php` demo which generates consistent results.

However this implementation of throttle operator is going to cause a lot of headaches I think since its behavior is different to the original throttle from RxJS and more developers will encounter the problem described above.
